server:
  port: 8081
spring:
  application:
    name: authentication-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${FRONT_URL}/login/oauth2/code/{registrationId}
            scope:
              - email
              - profile
              - openid
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}
    properties:
      retries: 10
      retry.backoff.ms: 2000
    admin:
      properties:
        offsets.topic.replication-factor: 1
        transactions.state.log.replication-factor: 1
        transactions.state.log.min.isr: 1
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/learning?currentSchema=authentication_service
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: authentication_service
        format_sql: true
    database: postgresql
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: authentication_service
    liquibase-schema: public
    database-change-log-table: authentication_service_databasechangelog
    database-change-log-lock-table: authentication_service_databasechangeloglock
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    ru.zeker: DEBUG
jwt:
  private-key-path: ${PRIVATE_KEY}
  public-key-path: ${PUBLIC_KEY}
  access:
    expiration: ${ACCESS_TOKEN_DURATION}
  refresh:
    expiration: ${REFRESH_TOKEN_DURATION}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  frontend-url: ${FRONT_URL}
  domain: http://localhost:8080
  version: 1
  cookie:
    domain: ${COOKIE_DOMAIN:}
    same-site: ${COOKIE_SAME_SITE:Lax}
    secure: ${COOKIE_SECURE:true}
  admin:
    username: ${ADMIN_EMAIL:admin@admin.com}
  security:
    password-history:
      max-count: 5
