server:
  port: 8083
spring:
  application:
    name: smtp-service
  kafka:
    properties:
      retries: 10
      retry.backoff.ms: 2000
    bootstrap-servers: ${KAFKA_HOST:localhost}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
      debug: true
app:
  frontend-url: ${FRONT_URL}
  company-name: ${COMPANY_NAME}
  links:
    email-verification: /email-confirmation
    password-reset: /password-reset