package ru.zeker.common.exception;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,
    MISSING_PARAMETER,
    VALIDATION_ERROR,
    INVALID_INPUT,
    TOKEN_EXPIRED,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_NOT_FOUND,
    AUTHORIZATION_ERROR,
    ACCESS_DENIED,
    BAD_CREDENTIALS,
    ACCOUNT_BLOCKED,
    LOCAL_AUTH_NOT_FOUND,
    O_AUTH2_PROVIDER,
    PASSWORD_HISTORY,
    TOO_MANY_RESEND_VERIFICATION,
    USER_ALREADY_ACTIVATION,
    USER_ALREADY_EXIST,
    USER_ALREADY_PASSWORD_BOUND,
    USER_ALREADY_ADMIN,
    USER_NOT_FOUND,
    USER_NOT_HAVE_ACTIVE_SESSIONS,
    UNSUPPORTED_TASK_TYPE,
    SOLUTION_NOT_FOUND,
    TASK_NOT_FOUND
}
